services:
  - name: web
    buildCommand: npm install
    startCommand: npm start
    env:
      MONGODB_URI: "<mongodb+srv://wiut00015881:<Sora2005>@cluster0.9qyy3xo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0>"
